version: "3.8"

services:
  db:
    image: postgres:15
    container_name: keynest-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: keynest_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:26.1.2
    platform: linux/amd64  # Forces the correct platform
    container_name: keynest-keycloak
    restart: unless-stopped
    command: ["start-dev", "--http-host=0.0.0.0"]
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/keynest_db  # 🔹 Shared database
      KC_DB_USERNAME: postgres
      KC_DB_PASSWORD: postgres
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    depends_on:
      - db
    ports:
      - "8080:8080"

  server:
    build:
      context: ./server  # Ensure this path is correct
      dockerfile: Dockerfile
    container_name: keynest-server
    restart: unless-stopped
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/keynest_db  # 🔹 Shared database
    depends_on:
      - db
      - keycloak
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app 
    command: npm run start:dev

volumes:
  postgres_data:
